#!/usr/bin/env bash
#
# craft (Coding with Rules, Autonomy, Feedback, Tests)
# test-epic-digest.sh — self-contained tests for epic-digest.sh (slice-057, roadmap B22): the
# autopilot's epic-end digest is generated by a helper the master only relays — never written from
# memory (slice-056 probes 3 and 4 paraphrased the candidates, the UX demo script and its dates).
#
# The case table was written before the helper. Run it directly:
#
#   bash scripts/test-epic-digest.sh
#
# It writes nothing outside its own mktemp directory (removed on exit).

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HELPER="$SCRIPT_DIR/epic-digest.sh"
for f in "$HELPER" "$SCRIPT_DIR/epic-entry-link.sh" "$SCRIPT_DIR/example-regions.sh"; do
  [[ -f "$f" ]] || { echo "FATAL: not found: $f" >&2; exit 2; }
done

PASS=0
FAIL=0
ok()  { printf '  PASS  %s\n' "$1"; PASS=$((PASS + 1)); }
bad() { printf '  FAIL  %s\n' "$1"; FAIL=$((FAIL + 1)); }

ROOT="$(mktemp -d)"
trap 'rm -rf "$ROOT"' EXIT
P="$ROOT/proj"
EPIC=".claude/plans/epic-900-demo.md"
SL="$P/.claude/project/slices"

reset() {
  rm -rf "$P"
  mkdir -p "$P/.claude/plans" "$SL"
}

# The UX demo script as a3 appends it — a fenced block whose `## ` line must not end the section,
# a blank line between the blocks, and the template's note above the first block (never printed).
DEMO='> Appended by `/craft:execute <epic> --autopilot` (a3). Never rewritten.

### slice-901 — Alpha
- Trigger: run `demo alpha`
- Try this:
  ```
  ## not a heading
  demo alpha --flag
  ```
- Expected: prints alpha
- Checked by: alpha-check
- Phase 5: verified by command (1/1, run 1, 2026-10-02T10:00:00Z)

### slice-902 — Beta
- Trigger: run `demo beta`
- Phase 5: Phase 5 by you ([W])'

# epic [<ux-section>] [<frontmatter>] — the epic plan; "-" as <ux-section> leaves the section out
epic() {
  local ux="${1-$DEMO}" fm="${2-> Epic-ID: epic-900
> Epic-Slug: demo}" uxblock=""
  [[ "$ux" == "-" ]] || uxblock="## UX Demo Script

$ux

"
  printf '# Epic 900 — Demo\n\n> Status: planning\n%s\n\n## Vision\n\nv\n\n## Slice Decomposition\n\n- [x] slice-901 — alpha — first\n- [x] slice-902 — beta — second\n\n%s## Autopilot Log\n\n- 2026-10-02T10:00:00Z · ▶ · epic-900 · run started\n\n## Recap Draft\n\n(not yet recorded)\n' \
    "$fm" "$uxblock" > "$P/$EPIC"
}

ARCH_A='# Slice 901 — Alpha

> Completed: 2026-10-02

## What

Adds the `alpha. mode` command
to the demo. It also mentions `- **Refactor candidate (autopilot, not applied):** x` inline.

## Why

- w

## Decisions

- **Refactor candidate (autopilot, not applied):** extract the parser — removes duplication
- **Other** — kept

```text
- **Refactor candidate (autopilot, not applied):** decoy in a fence
```

## Follow-ups

- R1-2 Light · Rethink · rename flag
  — wrap continued
- second follow-up

```text
- decoy follow-up in a fence
```

## Commits

- `abc1234` — feat: alpha'

ARCH_B='# Slice 902 — Beta

> Completed: 2026-10-02

## What

Beta prints beta

## Decisions

- **Phase 7 (autopilot): no refactor candidate**

## Commits

- `def5678` — feat: beta'

archives() {
  printf '%s\n' "${1-$ARCH_A}" > "$SL/slice-901-alpha.md"
  printf '%s\n' "${2-$ARCH_B}" > "$SL/slice-902-beta.md"
}

# run <args…> — stdout only; stderr and the exit code land in $ERR / $RC
run() {
  local o e
  e="$ROOT/stderr"
  o="$(cd "$P" && CLAUDE_PROJECT_DIR="$P" bash "$HELPER" "$@" 2>"$e")"
  RC=$?
  ERR="$(cat "$e")"
  OUT="$o"
}
expect() { # <label> <actual> <wanted>
  if [[ "$2" == "$3" ]]; then ok "$1"; else bad "$1 — got '$2', want '$3'"; fi
}
# expect_error <label> <exit> <reason> — a named error on stderr, nothing on stdout
expect_error() {
  if [[ "$RC" == "$2" && "$ERR" == *"ERROR=$3"* && -z "$OUT" ]]; then ok "$1"
  else bad "$1 — got exit $RC, stderr '$ERR', stdout '${OUT:0:80}'"; fi
}

WANT='✓ Autopilot — epic-900 complete: 2 slices on epic-900-demo
   slice-901 — Adds the `alpha. mode` command to the demo.
      follow-up: R1-2 Light · Rethink · rename flag — wrap continued
      follow-up: second follow-up
      refactor candidate: extract the parser — removes duplication
   slice-902 — Beta prints beta
   UX demo script — walk it before you answer (the epic plan'"'"'s ## UX Demo Script):
      ### slice-901 — Alpha
      - Trigger: run `demo alpha`
      - Try this:
        ```
        ## not a heading
        demo alpha --flag
        ```
      - Expected: prints alpha
      - Checked by: alpha-check
      - Phase 5: verified by command (1/1, run 1, 2026-10-02T10:00:00Z)

      ### slice-902 — Beta
      - Trigger: run `demo beta`
      - Phase 5: Phase 5 by you ([W])'

echo "CASES:"

# 1. the whole block, exactly — first sentence (joined lines, a period inside backticks is no end), follow-ups
#    (a wrapped bullet joined, a fenced decoy skipped), candidates at the line start only (an inline mention and a
#    fenced decoy list nothing; the no-candidate line lists nothing), the demo script as written
reset; epic; archives
run "$EPIC"
expect "exit 0 on a landed epic" "$RC" "0"
if [[ "$OUT" == "$WANT" ]]; then ok "the digest block is exactly the expected one"
else bad "the digest block differs:"; diff <(printf '%s\n' "$WANT") <(printf '%s\n' "$OUT") | sed 's/^/        /'; fi
expect "nothing on stderr on success" "$ERR" ""

# 2. the demo script byte-equal: the printed lines, indent removed, are the section from its first ### on
want_demo="$(printf '%s\n' "$DEMO" | sed -n '/^### /,$p')"
got_demo="$(printf '%s\n' "$OUT" | sed -n '/^      ### slice-901/,$p' | sed 's/^      //')"
expect "the UX demo script is printed byte-equal (indent removed)" "$got_demo" "$want_demo"

# 3. CRLF files read the same; the output has LF line ends
reset; epic; archives
for f in "$P/$EPIC" "$SL/slice-901-alpha.md" "$SL/slice-902-beta.md"; do
  sed 's/$/\r/' "$f" > "$f.crlf" && mv "$f.crlf" "$f"
done
run "$EPIC"
expect "CRLF epic plan and archives give the same digest" "$OUT" "$WANT"

# 4. first sentence: no sentence end → the whole first paragraph; ? and ! end a sentence
reset; epic; archives
run "$EPIC"
expect "no sentence end: the whole paragraph" "$(printf '%s\n' "$OUT" | grep '^   slice-902')" "   slice-902 — Beta prints beta"
reset; epic; archives "${ARCH_A/Adds the \`alpha. mode\` command/Does it work? Yes}"
run "$EPIC"
expect "a question mark ends the first sentence" "$(printf '%s\n' "$OUT" | grep '^   slice-901')" "   slice-901 — Does it work?"
reset; epic; archives "${ARCH_A/Adds the \`alpha. mode\` command/It works! Really}"
run "$EPIC"
expect "an exclamation mark ends the first sentence" "$(printf '%s\n' "$OUT" | grep '^   slice-901')" "   slice-901 — It works!"

# 5. a placeholder follow-up is no follow-up
reset; epic; archives "${ARCH_A/- second follow-up/- (none)}"
run "$EPIC"
expect "a '(none)' follow-up bullet lists nothing" "$(printf '%s\n' "$OUT" | grep -c 'follow-up:')" "1"

# 6. errors are named, exit non-zero, and print nothing on stdout — never a partial digest
reset; epic; archives
run
expect_error "no argument → usage" 2 "usage"
run ".claude/plans/epic-999-absent.md"
expect_error "an unreadable epic plan" 4 "epic_plan_unreadable"
reset; epic "$DEMO" "> Epic-Slug: demo"; archives
run "$EPIC"
expect_error "no Epic-ID in the frontmatter" 4 "epic_frontmatter:Epic-ID"
reset; epic "$DEMO" "> Epic-ID: epic-900"; archives
run "$EPIC"
expect_error "no Epic-Slug in the frontmatter" 4 "epic_frontmatter:Epic-Slug"
reset; epic; archives
printf '# Slice 902 — Beta\n\n> Status: reviewing\n> Slice-ID: slice-902\n' > "$P/.claude/plans/slice-902-beta.md"
run "$EPIC"
expect_error "a slice still open (plan, not landed)" 5 "not_landed:slice-902:plan"
# an archive missing (and no plan): epic-entry-link.sh reads the slice as missing, so the helper stops before its own
# archive_missing guard, which only a race between the two reads can reach
reset; epic; printf '%s\n' "$ARCH_A" > "$SL/slice-901-alpha.md"
run "$EPIC"
expect_error "an archive missing (slice neither planned nor landed)" 5 "not_landed:slice-902:missing"
reset; epic; archives
printf '%s\n' "$ARCH_B" > "$SL/slice-902-beta-2.md"
run "$EPIC"
expect_error "two archives for one slice" 6 "archive_ambiguous:slice-902"
reset; epic; archives "$ARCH_A" "${ARCH_B/\## What/## Summary}"   # \# — a leading # would anchor the pattern
run "$EPIC"
expect_error "an archive without ## What" 6 "what_missing:slice-902"
reset; epic; archives "$ARCH_A" "${ARCH_B/Beta prints beta/}"
run "$EPIC"
expect_error "an archive with an empty ## What" 6 "what_missing:slice-902"
reset; epic "-"; archives
run "$EPIC"
expect_error "no ## UX Demo Script section" 7 "ux_demo_script_missing"
reset; epic '> note

(no slices landed yet)'; archives
run "$EPIC"
expect_error "a UX demo script with no block yet" 7 "ux_demo_script_empty"
reset; epic "-"; archives
perl -0pi -e 's/\n\nv\n/\n\n```\n## UX Demo Script\n\n### slice-901 — decoy\n```\n/' "$P/$EPIC"
run "$EPIC"
expect_error "a heading inside a fence is not the section" 7 "ux_demo_script_missing"

echo
echo "RESULT: $PASS passed, $FAIL failed"
[[ $FAIL -eq 0 ]]
